//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;


    public class V_TicketType
    {
        public long? Id { get; set; }

        public string TypeName { get; set; }

        public string BuildInCode { get; set; }

    }
}
