//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OutgoingEmail
    {
        public long Id { get; set; }
        public string CustomerCode { get; set; }
        public string ToEmail { get; set; }
        public string CCEmail { get; set; }
        public string ReplyEmail { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string HistorySend { get; set; }
        public string Attachment { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
