//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PartnerCard
    {
        public string Id { get; set; }
        public string Currency { get; set; }
        public string CardType { get; set; }
        public string CardNumber { get; set; }
        public string CardHolderName { get; set; }
        public string CardExpiry { get; set; }
        public bool IsDefault { get; set; }
        public string MerchantCardReference { get; set; }
        public string TerminalId { get; set; }
        public bool Active { get; set; }
        public string CardAddressStreet { get; set; }
        public string CardCity { get; set; }
        public string CardCountry { get; set; }
        public string CardState { get; set; }
        public string CardZipCode { get; set; }
        public string CardPhone { get; set; }
        public string CardEmail { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string CardFirstName { get; set; }
        public string CardLastName { get; set; }
        public Nullable<long> MxMerchant_Id { get; set; }
        public string MxMerchant_CardId { get; set; }
        public string MxMerchant_Token { get; set; }
        public Nullable<bool> IsRecurring { get; set; }
        public string PartnerCode { get; set; }
    }
}
