//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SalesLead
    {
        public string Id { get; set; }
        public Nullable<int> SL_Status { get; set; }
        public string SL_StatusName { get; set; }
        public Nullable<int> PotentialRateScore { get; set; }
        public string MemberNumber { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string Features_Interes { get; set; }
        public string Features_Interes_other { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public string L_SalonName { get; set; }
        public string L_Address { get; set; }
        public string L_State { get; set; }
        public string L_City { get; set; }
        public string L_Zipcode { get; set; }
        public string L_Country { get; set; }
        public string L_Phone { get; set; }
        public string L_ContactName { get; set; }
        public string L_ContactPhone { get; set; }
        public string L_MoreInfo { get; set; }
        public string L_Type { get; set; }
        public string L_Password { get; set; }
        public string L_Email { get; set; }
        public Nullable<bool> L_IsVerify { get; set; }
        public Nullable<bool> L_IsSendMail { get; set; }
        public string L_CreateTrialBy { get; set; }
        public Nullable<System.DateTime> L_CreateTrialAt { get; set; }
        public string L_Product { get; set; }
        public string L_Version { get; set; }
        public string SalonTimeZone { get; set; }
        public string SalonTimeZone_Number { get; set; }
        public Nullable<long> TeamNumber { get; set; }
        public string Interaction_Status { get; set; }
        public string CallOfNumber { get; set; }
        public string MemberName { get; set; }
        public string TeamName { get; set; }
        public string L_License_Name { get; set; }
        public string L_License_Code { get; set; }
        public string LastUpdateDesc { get; set; }
        public Nullable<System.DateTime> LastNoteAt { get; set; }
        public string LastNote { get; set; }
        public Nullable<int> Interaction_Status_Id { get; set; }
        public string CreateByMemberNumber { get; set; }
    }
}
