//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar_Event
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Color { get; set; }
        public string TicketId { get; set; }
        public string TicketName { get; set; }
        public string GMT { get; set; }
        public string TimeZone { get; set; }
        public string StartEvent { get; set; }
        public string EndEvent { get; set; }
        public Nullable<int> Done { get; set; }
        public Nullable<System.DateTime> LastUpdateAt { get; set; }
        public string LastUpdateBy { get; set; }
        public string LastUpdateByNumber { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string MemberNumber { get; set; }
        public string Type { get; set; }
        public string SalesLeadId { get; set; }
        public string SalesLeadName { get; set; }
        public Nullable<int> DemoSchedulerId { get; set; }
        public string Location { get; set; }
        public string AttendeesNumber { get; set; }
        public string AttendeesName { get; set; }
        public string GoogleCalendarId { get; set; }
        public string MemberName { get; set; }
        public Nullable<System.DateTime> StartUTC { get; set; }
        public Nullable<System.DateTime> EndUTC { get; set; }
        public string ETag { get; set; }
        public string REF { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
