//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Bundle_Device
    {
        public long Id { get; set; }
        public Nullable<long> Bundle_Id { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string ModelCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ModelName { get; set; }
    }
}
