//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class License_Product_Item
    {
        public long Id { get; set; }
        public string License_Product_Id { get; set; }
        public Nullable<int> CountWarning { get; set; }
        public string License_Item_Code { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<bool> Enable { get; set; }
    }
}
