//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnrichcousBOEntities : DbContext
    {
        public EnrichcousBOEntities()
            : base("name=EnrichcousBOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_FunctionInPage> A_FunctionInPage { get; set; }
        public virtual DbSet<A_GrandAccess> A_GrandAccess { get; set; }
        public virtual DbSet<A_Page> A_Page { get; set; }
        public virtual DbSet<A_Role> A_Role { get; set; }
        public virtual DbSet<Ad_Country> Ad_Country { get; set; }
        public virtual DbSet<Ad_USAState> Ad_USAState { get; set; }
        public virtual DbSet<C_BossStore> C_BossStore { get; set; }
        public virtual DbSet<C_Customer> C_Customer { get; set; }
        public virtual DbSet<C_CustomerAdditionalInfo> C_CustomerAdditionalInfo { get; set; }
        public virtual DbSet<C_CustomerCard> C_CustomerCard { get; set; }
        public virtual DbSet<C_CustomerContact> C_CustomerContact { get; set; }
        public virtual DbSet<C_CustomerGiftcard> C_CustomerGiftcard { get; set; }
        public virtual DbSet<C_CustomerSupportingInfo> C_CustomerSupportingInfo { get; set; }
        public virtual DbSet<C_CustomerTransaction> C_CustomerTransaction { get; set; }
        public virtual DbSet<C_DemoScheduler> C_DemoScheduler { get; set; }
        public virtual DbSet<C_GiftCardsOrderingForm> C_GiftCardsOrderingForm { get; set; }
        public virtual DbSet<C_MerchantProcess> C_MerchantProcess { get; set; }
        public virtual DbSet<C_MerchantProcessing> C_MerchantProcessing { get; set; }
        public virtual DbSet<C_MerchantSubscribe> C_MerchantSubscribe { get; set; }
        public virtual DbSet<C_OutgoingEmail> C_OutgoingEmail { get; set; }
        public virtual DbSet<C_Partner> C_Partner { get; set; }
        public virtual DbSet<C_PartnerCard> C_PartnerCard { get; set; }
        public virtual DbSet<C_Questionare> C_Questionare { get; set; }
        public virtual DbSet<C_Questionare_NonTechnician> C_Questionare_NonTechnician { get; set; }
        public virtual DbSet<C_Questionare_Technician> C_Questionare_Technician { get; set; }
        public virtual DbSet<C_SalesLead> C_SalesLead { get; set; }
        public virtual DbSet<C_SalesLead_Interaction_Status> C_SalesLead_Interaction_Status { get; set; }
        public virtual DbSet<C_SalesLead_Status> C_SalesLead_Status { get; set; }
        public virtual DbSet<Calendar_Event> Calendar_Event { get; set; }
        public virtual DbSet<Dejavo_Datasheet> Dejavo_Datasheet { get; set; }
        public virtual DbSet<Device_Features> Device_Features { get; set; }
        public virtual DbSet<Document_Category> Document_Category { get; set; }
        public virtual DbSet<Document_File> Document_File { get; set; }
        public virtual DbSet<External_Embed> External_Embed { get; set; }
        public virtual DbSet<Form_CustomizeItems> Form_CustomizeItems { get; set; }
        public virtual DbSet<Form_CustomizeRequest> Form_CustomizeRequest { get; set; }
        public virtual DbSet<I_Bundle> I_Bundle { get; set; }
        public virtual DbSet<I_Bundle_Device> I_Bundle_Device { get; set; }
        public virtual DbSet<I_ProcessSetting> I_ProcessSetting { get; set; }
        public virtual DbSet<I_ProgressFill> I_ProgressFill { get; set; }
        public virtual DbSet<ImportExcelHistory> ImportExcelHistories { get; set; }
        public virtual DbSet<IMSLog> IMSLogs { get; set; }
        public virtual DbSet<License_Item> License_Item { get; set; }
        public virtual DbSet<License_Item_Group> License_Item_Group { get; set; }
        public virtual DbSet<License_Product> License_Product { get; set; }
        public virtual DbSet<License_Product_Item> License_Product_Item { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<M_Ads> M_Ads { get; set; }
        public virtual DbSet<M_Campaign> M_Campaign { get; set; }
        public virtual DbSet<O_Device> O_Device { get; set; }
        public virtual DbSet<O_MerchantForm> O_MerchantForm { get; set; }
        public virtual DbSet<O_Order_Refund> O_Order_Refund { get; set; }
        public virtual DbSet<O_Orders> O_Orders { get; set; }
        public virtual DbSet<O_Orders_Service_Renewal> O_Orders_Service_Renewal { get; set; }
        public virtual DbSet<O_Product> O_Product { get; set; }
        public virtual DbSet<O_Product_Line> O_Product_Line { get; set; }
        public virtual DbSet<O_Product_Model> O_Product_Model { get; set; }
        public virtual DbSet<Option_Config> Option_Config { get; set; }
        public virtual DbSet<Order_Carrier> Order_Carrier { get; set; }
        public virtual DbSet<Order_Products> Order_Products { get; set; }
        public virtual DbSet<Order_Subcription> Order_Subcription { get; set; }
        public virtual DbSet<Order_UPSPackage> Order_UPSPackage { get; set; }
        public virtual DbSet<Order_UPSTracking> Order_UPSTracking { get; set; }
        public virtual DbSet<P_BankSupport> P_BankSupport { get; set; }
        public virtual DbSet<P_BonusStrategySetting> P_BonusStrategySetting { get; set; }
        public virtual DbSet<P_CommEmployeeSetting> P_CommEmployeeSetting { get; set; }
        public virtual DbSet<P_CommLevelSetting> P_CommLevelSetting { get; set; }
        public virtual DbSet<P_Department> P_Department { get; set; }
        public virtual DbSet<P_EmployeePayroll> P_EmployeePayroll { get; set; }
        public virtual DbSet<P_EmployeePayrollPayment> P_EmployeePayrollPayment { get; set; }
        public virtual DbSet<P_Level> P_Level { get; set; }
        public virtual DbSet<P_Member> P_Member { get; set; }
        public virtual DbSet<P_MemberAvailableTime> P_MemberAvailableTime { get; set; }
        public virtual DbSet<P_MemberLevel> P_MemberLevel { get; set; }
        public virtual DbSet<P_MemberSubscription> P_MemberSubscription { get; set; }
        public virtual DbSet<P_MemberType> P_MemberType { get; set; }
        public virtual DbSet<P_Notification> P_Notification { get; set; }
        public virtual DbSet<P_NotificationMapping> P_NotificationMapping { get; set; }
        public virtual DbSet<P_NotificationTemplate> P_NotificationTemplate { get; set; }
        public virtual DbSet<P_PayrollFiles> P_PayrollFiles { get; set; }
        public virtual DbSet<PO> POes { get; set; }
        public virtual DbSet<PO_Detail> PO_Detail { get; set; }
        public virtual DbSet<PO_Detail_Checkin> PO_Detail_Checkin { get; set; }
        public virtual DbSet<PO_Request> PO_Request { get; set; }
        public virtual DbSet<S_AddonSchedulerActivation> S_AddonSchedulerActivation { get; set; }
        public virtual DbSet<Store_Services> Store_Services { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<SystemConfiguration> SystemConfigurations { get; set; }
        public virtual DbSet<T_EmailTemplate> T_EmailTemplate { get; set; }
        public virtual DbSet<T_EmailTemplateGroup> T_EmailTemplateGroup { get; set; }
        public virtual DbSet<T_FileRelated> T_FileRelated { get; set; }
        public virtual DbSet<T_Priority> T_Priority { get; set; }
        public virtual DbSet<T_Project_Milestone> T_Project_Milestone { get; set; }
        public virtual DbSet<T_Project_Milestone_Member> T_Project_Milestone_Member { get; set; }
        public virtual DbSet<T_Project_Milestone_Notes> T_Project_Milestone_Notes { get; set; }
        public virtual DbSet<T_Project_Stage> T_Project_Stage { get; set; }
        public virtual DbSet<T_Project_Stage_Members> T_Project_Stage_Members { get; set; }
        public virtual DbSet<T_RemindersTicket> T_RemindersTicket { get; set; }
        public virtual DbSet<T_SupportTicket> T_SupportTicket { get; set; }
        public virtual DbSet<T_Tags> T_Tags { get; set; }
        public virtual DbSet<T_TicketAttribute> T_TicketAttribute { get; set; }
        public virtual DbSet<T_TicketFeedback> T_TicketFeedback { get; set; }
        public virtual DbSet<T_TicketSeverity> T_TicketSeverity { get; set; }
        public virtual DbSet<T_TicketStage_Status> T_TicketStage_Status { get; set; }
        public virtual DbSet<T_TicketStatus> T_TicketStatus { get; set; }
        public virtual DbSet<T_TicketStatusMapping> T_TicketStatusMapping { get; set; }
        public virtual DbSet<T_TicketTranferMapping> T_TicketTranferMapping { get; set; }
        public virtual DbSet<T_TicketType> T_TicketType { get; set; }
        public virtual DbSet<T_TicketTypeMapping> T_TicketTypeMapping { get; set; }
        public virtual DbSet<T_TicketUpdateLog> T_TicketUpdateLog { get; set; }
        public virtual DbSet<Ts_Task> Ts_Task { get; set; }
        public virtual DbSet<Ts_TaskTemplateCategory> Ts_TaskTemplateCategory { get; set; }
        public virtual DbSet<Ts_TaskTemplateField> Ts_TaskTemplateField { get; set; }
        public virtual DbSet<UploadMoreFile> UploadMoreFiles { get; set; }
        public virtual DbSet<Vendor> Vendors { get; set; }
    }
}
