//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_Order_Refund
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string OrderCode { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<decimal> RefundAmout { get; set; }
        public string Reason { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
    }
}
