//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_Product_Model
    {
        public string ModelCode { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Status { get; set; }
        public string Picture { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ModelName { get; set; }
        public Nullable<bool> DeviceRequired { get; set; }
        public Nullable<bool> MerchantOnboarding { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
    }
}
