//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_CommLevelSetting
    {
        public long Id { get; set; }
        public Nullable<decimal> CommPercent_Override { get; set; }
        public Nullable<int> LevelNumber { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<decimal> CommPercent_Directly { get; set; }
        public Nullable<decimal> CommPercent_ManagementOffice { get; set; }
        public string ProductTypeCode { get; set; }
        public string ProductTypeName { get; set; }
    }
}
