//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Department
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string LeaderNumber { get; set; }
        public string LeaderName { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<long> ParentDepartmentId { get; set; }
        public string ParentDepartmentName { get; set; }
        public string GroupMemberNumber { get; set; }
        public string GroupMemberName { get; set; }
        public string Type { get; set; }
        public string SupervisorNumber { get; set; }
        public string SupervisorName { get; set; }
        public string SaleStates { get; set; }
        public string PartnerCode { get; set; }
        public string PartnerName { get; set; }
    }
}
