//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MemberSubscription
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PersonalEmail { get; set; }
        public string CellPhone { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string DriverLicense { get; set; }
        public string SocialSecurity { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string ReferedByNumber { get; set; }
        public string ReferedByName { get; set; }
        public string MemberType { get; set; }
        public string MemberTypeName { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string ConfirmBy { get; set; }
        public Nullable<System.DateTime> ConfirmAt { get; set; }
        public string MemberNumber { get; set; }
    }
}
