//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_NotificationMapping
    {
        public int Id { get; set; }
        public string MemberNumber { get; set; }
        public int NotificationId { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<System.DateTime> ViewTime { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
    
        public virtual P_Notification P_Notification { get; set; }
    }
}
