//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO
    {
        public string POCode { get; set; }
        public Nullable<long> VendorId { get; set; }
        public string VendorName { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Status { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string SaleOrderNumber { get; set; }
        public Nullable<bool> AllCheckedIn { get; set; }
    }
}
