//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EmailTemplate
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> TemplateGroupId { get; set; }
        public string TemplateGroupName { get; set; }
        public string Content { get; set; }
    }
}
