//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Project_Stage
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string Desc { get; set; }
        public Nullable<int> MemberCount { get; set; }
        public string BuildInCode { get; set; }
        public string LeaderName { get; set; }
        public string LeaderNumber { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
