//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Promotion.Mango.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TicketTranferMapping
    {
        public int Id { get; set; }
        public Nullable<long> TicketId { get; set; }
        public Nullable<long> FromTicketId { get; set; }
        public Nullable<long> ToTicketId { get; set; }
        public string FromProjectId { get; set; }
        public string ToProjectId { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateByName { get; set; }
        public string CreateByMemberNumner { get; set; }
        public string Note { get; set; }
    }
}
