//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CustomerPayment
    {
        public string Id { get; set; }
        public string TransactionCode { get; set; }
        public string OrderCode { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> MerchantFee { get; set; }
        public Nullable<decimal> PayerFee { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string Status { get; set; }
        public string StatusCode { get; set; }
        public string Method { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string CardNumber { get; set; }
        public string CreateBy { get; set; }
        public string PaymentNote { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
    }
}
