//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Questionare_NonTechnician
    {
        public string Id { get; set; }
        public string QuestionareId { get; set; }
        public string Name { get; set; }
        public string Job { get; set; }
        public string Pay { get; set; }
        public Nullable<bool> AdjustViewPayroll { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
    }
}
