//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SalesLead_Status
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<bool> PendingCloseContract { get; set; }
        public string Color { get; set; }
    }
}
