//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumValue
    {
        public int ID { get; set; }
        public string Namespace { get; set; }
        public string Value { get; set; }
        public string Name { get; set; }
        public string IconUrl { get; set; }
        public Nullable<int> Order { get; set; }
    }
}
