//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ProcessSetting
    {
        public long Id { get; set; }
        public string FieldName { get; set; }
        public Nullable<bool> Requirement { get; set; }
        public string FieldType { get; set; }
        public Nullable<bool> IsCheck { get; set; }
    }
}
