//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class License_Product
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> isAddon { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Type { get; set; }
        public string SubscriptionDuration { get; set; }
        public Nullable<int> SubscriptionEndWarningDays { get; set; }
        public string Code { get; set; }
        public string Code_POSSystem { get; set; }
        public Nullable<bool> AllowDemo { get; set; }
        public Nullable<bool> AllowSlice { get; set; }
        public Nullable<int> Trial_Days { get; set; }
        public Nullable<decimal> Promotion_Price { get; set; }
        public Nullable<int> Promotion_Apply_Months { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> NumberOfPeriod { get; set; }
        public Nullable<int> Trial_Months { get; set; }
        public Nullable<int> Promotion_Time_To_Available { get; set; }
        public Nullable<int> GiftCardQuantity { get; set; }
        public Nullable<decimal> PartnerPrice { get; set; }
        public Nullable<decimal> MembershipPrice { get; set; }
        public Nullable<decimal> ActivationFee { get; set; }
        public Nullable<int> PreparingDays { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string PeriodRecurring { get; set; }
        public Nullable<decimal> InteractionFee { get; set; }
        public Nullable<bool> DeploymentTiketAuto { get; set; }
        public Nullable<int> FlagDeactivateExpires { get; set; }
        public Nullable<int> SiteId { get; set; }
    }
}
