//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Campaign
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> NumberOfPeopleReached { get; set; }
        public Nullable<int> TotalSuccess { get; set; }
        public Nullable<int> TotalFailed { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> LastUpdateAt { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<int> Status { get; set; }
        public string Note { get; set; }
    }
}
