//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_Product
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string ProductLineCode { get; set; }
        public string Picture { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
