//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_UPSTracking
    {
        public string Id { get; set; }
        public string OrderCode { get; set; }
        public string TrackingNumber { get; set; }
        public string ShippmentDescription { get; set; }
        public string ShipperStreetAddress { get; set; }
        public string ShipperState { get; set; }
        public string ShipperCity { get; set; }
        public string ShipperZipcode { get; set; }
        public string ShipperCountry { get; set; }
        public string Status { get; set; }
        public Nullable<int> Active { get; set; }
        public string UPS_Service_Code { get; set; }
        public string ActivityStatus { get; set; }
    }
}
