//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EmployeeBankCard
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public string BankName { get; set; }
        public string BranchNameBank { get; set; }
        public string MemberNumber { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Note { get; set; }
    }
}
