//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_EmployeePayroll
    {
        public long Id { get; set; }
        public string RecipientMemberNumber { get; set; }
        public string RecipientName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Comment { get; set; }
        public string ContractId { get; set; }
        public string CustomerTransactionId { get; set; }
        public string CustomerName { get; set; }
        public string Type { get; set; }
        public string TypeComm { get; set; }
        public Nullable<bool> OverrideComm { get; set; }
        public Nullable<bool> Paid { get; set; }
        public string PaidNumber { get; set; }
        public string PaidInfo { get; set; }
        public string TakeBackMoney_Comment { get; set; }
        public string TakeBackMoney_ExceptFromPaidNumber { get; set; }
        public Nullable<bool> TakeBackMoney { get; set; }
        public string PayrollMonth { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsCalculate { get; set; }
        public Nullable<decimal> TransactionAmount { get; set; }
    }
}
