//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Level
    {
        public int Level { get; set; }
        public string LevelName { get; set; }
        public string Decription { get; set; }
        public Nullable<int> OptionPromote1_RequirementLevel { get; set; }
        public Nullable<int> OptionPromote1_RequirementLevel_Qty { get; set; }
        public Nullable<int> OptionPromote1_RequirementLevel_RequimentEveryLevel_QtyContract { get; set; }
        public Nullable<int> OptionPromote2_RequimentQtyContractReached { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
