//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_PayrollFiles
    {
        public int Id { get; set; }
        public System.DateTime PayrollDate { get; set; }
        public string FilePath { get; set; }
        public string MemberNumber { get; set; }
        public Nullable<bool> IsSendMail { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string FileName { get; set; }
        public string EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
