//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSExportFile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string HangfireJobId { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
        public string MemberNumber { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateAt { get; set; }
    }
}
