//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyMeetingMapping
    {
        public int Id { get; set; }
        public int MeetingSurveyId { get; set; }
        public string MemberNumber { get; set; }
        public Nullable<int> Rate { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string Action { get; set; }
    }
}
