//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyMeeting
    {
        public int Id { get; set; }
        public string SurveyName { get; set; }
        public Nullable<bool> Status { get; set; }
        public string AssignMemberNumbers { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> MinuteDuration { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string Question { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
