//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyIM
    {
        public int Id { get; set; }
        public string MemberNumber { get; set; }
        public string Action { get; set; }
        public Nullable<int> Satisfaction { get; set; }
        public Nullable<int> Bug { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> MeetTheMeed { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    }
}
