//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Project_Milestone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Project_Milestone()
        {
            this.T_Project_Milestone_Member = new HashSet<T_Project_Milestone_Member>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string ParentId { get; set; }
        public string ParentName { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Active { get; set; }
        public string Description { get; set; }
        public Nullable<int> Order { get; set; }
        public string TicketType { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateByNumber { get; set; }
        public string BuildInCode { get; set; }
        public string LeaderNumber { get; set; }
        public string LeaderName { get; set; }
        public string ManagerNumber { get; set; }
        public string ManagerName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Project_Milestone_Member> T_Project_Milestone_Member { get; set; }
    }
}
