//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SupportTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_SupportTicket()
        {
            this.T_FileRelated = new HashSet<T_FileRelated>();
            this.T_RemindersTicket = new HashSet<T_RemindersTicket>();
            this.T_TicketStatusMapping = new HashSet<T_TicketStatusMapping>();
            this.T_TicketTypeMapping = new HashSet<T_TicketTypeMapping>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string ContactEmail { get; set; }
        public string CreateByNumber { get; set; }
        public string CreateByName { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string StatusId { get; set; }
        public string StatusName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string TypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public string OpenByMemberNumber { get; set; }
        public string OpenByName { get; set; }
        public Nullable<bool> Visible { get; set; }
        public Nullable<bool> KB { get; set; }
        public string ProductId { get; set; }
        public string Productname { get; set; }
        public string RelatedTicketId { get; set; }
        public string SubscribeMemberNumber { get; set; }
        public string SubscribeName { get; set; }
        public string AssignedToMemberNumber { get; set; }
        public string AssignedToMemberName { get; set; }
        public Nullable<long> SeverityId { get; set; }
        public string SeverityName { get; set; }
        public Nullable<long> GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public string CloseByMemberNumber { get; set; }
        public string CloseByName { get; set; }
        public string UpdateTicketHistory { get; set; }
        public string ReassignedToMemberNumber { get; set; }
        public string ReassignedToMemberName { get; set; }
        public string EscalateToStageId { get; set; }
        public string EscalateToStageNote { get; set; }
        public string FeedbackTicketHistory { get; set; }
        public string GlobalStatus { get; set; }
        public string OrderCode { get; set; }
        public string Tags { get; set; }
        public string ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string MilestoneId { get; set; }
        public string MilestoneName { get; set; }
        public string Mail_MessageId { get; set; }
        public string PriorityName { get; set; }
        public string FixedMilestoneId { get; set; }
        public string FixedMilestoneName { get; set; }
        public string StageId { get; set; }
        public string StageName { get; set; }
        public string AttributeIds { get; set; }
        public string IdentityType { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string VersionId { get; set; }
        public string VersionName { get; set; }
        public string UploadIds { get; set; }
        public string AffectedVersionId { get; set; }
        public string FixedVersionId { get; set; }
        public string TagName { get; set; }
        public string AssignJson { get; set; }
        public string TagMemberNumber { get; set; }
        public string TagMemberName { get; set; }
        public string Note { get; set; }
        public string AffectedVersionName { get; set; }
        public string FixedVersionName { get; set; }
        public string OtherGroupId { get; set; }
        public string OtherGroupName { get; set; }
        public Nullable<System.DateTime> EstimatedCompletionTimeFrom { get; set; }
        public Nullable<System.DateTime> EstimatedCompletionTimeTo { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public string DeadlineHangfireJobId { get; set; }
        public Nullable<int> SiteId { get; set; }
        public string JiraIssueLink { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_FileRelated> T_FileRelated { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RemindersTicket> T_RemindersTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TicketStatusMapping> T_TicketStatusMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TicketTypeMapping> T_TicketTypeMapping { get; set; }
    }
}
