//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TicketType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_TicketType()
        {
            this.T_TicketTypeMapping = new HashSet<T_TicketTypeMapping>();
        }
    
        public long Id { get; set; }
        public string TypeName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> Order { get; set; }
        public string SpecialType { get; set; }
        public string BuildInCode { get; set; }
        public string StageId { get; set; }
        public string StageName { get; set; }
        public string ProjectVersionId { get; set; }
        public string ProjectVersionName { get; set; }
        public string ProjectId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TicketTypeMapping> T_TicketTypeMapping { get; set; }
    }
}
