//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TicketStage_Status
    {
        public string Id { get; set; }
        public Nullable<long> TicketId { get; set; }
        public string StageId { get; set; }
        public string StageName { get; set; }
        public string AffectedVersion { get; set; }
        public string FixedVersion { get; set; }
        public string AssignedMember_Numbers { get; set; }
        public string AssignedMember_Names { get; set; }
        public Nullable<long> StatusId { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string ProjectVersionId { get; set; }
        public string ProjectVersionName { get; set; }
        public Nullable<System.DateTime> OpenDate { get; set; }
        public Nullable<long> TypeId { get; set; }
    }
}
