//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TicketTypeMapping
    {
        public int Id { get; set; }
        public Nullable<long> TypeId { get; set; }
        public string TypeName { get; set; }
        public Nullable<long> TicketId { get; set; }
    
        public virtual T_TicketType T_TicketType { get; set; }
        public virtual T_SupportTicket T_SupportTicket { get; set; }
    }
}
