//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TicketStatusMapping
    {
        public int Id { get; set; }
        public long StatusId { get; set; }
        public string StatusName { get; set; }
        public long TicketId { get; set; }
    
        public virtual T_TicketStatus T_TicketStatus { get; set; }
        public virtual T_SupportTicket T_SupportTicket { get; set; }
    }
}
