//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ts_Task
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> TicketId { get; set; }
        public string TicketName { get; set; }
        public Nullable<bool> Complete { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> ReminderWeeklyAt { get; set; }
        public Nullable<int> ReminderMonthlyAt { get; set; }
        public string AssignedToMemberNumber { get; set; }
        public string AssignedToMemberName { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<long> ParentTaskId { get; set; }
        public string ParentTaskName { get; set; }
        public string CreateByMemberNumber { get; set; }
        public Nullable<bool> Reminded { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> TaskTemplateCategoryId { get; set; }
        public Nullable<bool> Requirement { get; set; }
        public string Note { get; set; }
    }
}
