//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwilioAccount
    {
        public int Id { get; set; }
        public string StoreCode { get; set; }
        public string Name { get; set; }
        public string SId { get; set; }
        public string AuthToken { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string CustomerProfileSId { get; set; }
        public string Status { get; set; }
        public string OwnerAccountSid { get; set; }
    }
}
