//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrichcousBackOffice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwilioCustomerProfile
    {
        public int Id { get; set; }
        public string StoreCode { get; set; }
        public string CustomerProfileSId { get; set; }
        public string TwilioAccountSId { get; set; }
        public string BusinessName { get; set; }
        public string BusinessStreetAddress { get; set; }
        public string BusinessStreetAddress2 { get; set; }
        public string BusinessCity { get; set; }
        public string BusinessStateProvinceRegion { get; set; }
        public string BusinessPostalCode { get; set; }
        public string BusinessCountry { get; set; }
        public string BusinessContactFirstName { get; set; }
        public string BusinessContactLastName { get; set; }
        public string BusinessContactEmail { get; set; }
        public string BusinessContactPhone { get; set; }
        public string BusinessWebsite { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public string NotificationEmail { get; set; }
    }
}
