//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CustomerTransaction
    {
        public string Id { get; set; }
        public string Card { get; set; }
        public string PaymentStatus { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseText { get; set; }
        public string ApprovalCode { get; set; }
        public string AvsResponse { get; set; }
        public string CVVResponse { get; set; }
        public string UniqueREF { get; set; }
        public string CustomerCode { get; set; }
        public string StoreCode { get; set; }
        public string OrdersCode { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string BankName { get; set; }
        public string CardNumber { get; set; }
        public string MxMerchant_id { get; set; }
        public string MxMerchant_token { get; set; }
        public string MxMerchant_authMessage { get; set; }
        public string CreateBy { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentNote { get; set; }
    }
}
