//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CustomerContact
    {
        public long Id { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string Name { get; set; }
        public string Authorization { get; set; }
        public string PreferredLanguage { get; set; }
        public string PreferredContact { get; set; }
        public string PhoneNumber { get; set; }
        public string Relationship { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
    }
}
