//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GiftCardsOrderingForm
    {
        public int Id { get; set; }
        public string CustomerCode { get; set; }
        public string OrderCode { get; set; }
        public string SalesPerson { get; set; }
        public string SalonHours { get; set; }
        public string ProductCode { get; set; }
        public string FrontDesign { get; set; }
        public string BackDesign { get; set; }
        public string FrontDesignFiles { get; set; }
        public string BackDesignFiles { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
    }
}
