//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_MerchantProcess
    {
        public long Id { get; set; }
        public string CustomerCode { get; set; }
        public string M_ID { get; set; }
        public string Status { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Model { get; set; }
        public string InvNumber { get; set; }
        public string OrderProductId { get; set; }
    }
}
