//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Questionare
    {
        public string Id { get; set; }
        public Nullable<long> CustomerId { get; set; }
        public string CustomerCode { get; set; }
        public string SalonName { get; set; }
        public string ContactName { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<bool> AllowTexting { get; set; }
        public string SalonHours { get; set; }
        public Nullable<bool> EthernetWrite { get; set; }
        public string ServiceFee { get; set; }
        public string TechOrder { get; set; }
        public Nullable<double> DollarAmount { get; set; }
        public string FileAttach { get; set; }
        public Nullable<bool> ComboSpecialDiscount { get; set; }
        public string Note { get; set; }
        public Nullable<bool> PayoutCreditCard { get; set; }
        public string AUTHORIZED_Seller { get; set; }
        public string AUTHORIZED_Tech { get; set; }
        public string OtherRequest { get; set; }
        public Nullable<System.DateTime> DateSubmit { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UpdateHistory { get; set; }
        public Nullable<bool> CustomerAddTips { get; set; }
        public Nullable<bool> SuggestPercentTip { get; set; }
        public string SalonEmail { get; set; }
        public string OwnerEmail { get; set; }
        public Nullable<bool> ChargeFeeTips { get; set; }
        public Nullable<bool> CommissionProductSales { get; set; }
        public string SalonAddress1 { get; set; }
        public string SalonAddress2 { get; set; }
        public string SalonCity { get; set; }
        public string SalonState { get; set; }
        public string SalonZipcode { get; set; }
        public string SalonPhone { get; set; }
        public string SalonTimeZone { get; set; }
        public string Drivers_License_Front_Image { get; set; }
        public string Drivers_License_Back_Image { get; set; }
        public string SS4 { get; set; }
        public string VoidedBusinessCheck { get; set; }
        public string SendToOwnersEmail { get; set; }
    }
}
