//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMSLog
    {
        public string Id { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string Url { get; set; }
        public string RequestUrl { get; set; }
        public string RequestMethod { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<bool> Success { get; set; }
        public string JsonRequest { get; set; }
        public string JsonRespone { get; set; }
        public string Description { get; set; }
        public string SalonName { get; set; }
    }
}
