//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_MerchantForm
    {
        public long Id { get; set; }
        public string MerchantCode { get; set; }
        public string MerchantName { get; set; }
        public string TemplateName { get; set; }
        public string PDF_URL { get; set; }
        public string Status { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<long> OrderId { get; set; }
        public Nullable<long> TerminalId { get; set; }
        public Nullable<bool> Signed { get; set; }
        public Nullable<bool> Send { get; set; }
        public Nullable<System.DateTime> SendAt { get; set; }
        public string AgreementId { get; set; }
        public string SendByAgent { get; set; }
        public Nullable<bool> forNUVEI { get; set; }
    }
}
