//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_Orders
    {
        public long Id { get; set; }
        public string OrdersCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string SalesMemberNumber { get; set; }
        public string SalesName { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedHistory { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalHardware_Amount { get; set; }
        public Nullable<decimal> ShippingFee { get; set; }
        public Nullable<decimal> Service_Amount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<double> DiscountPercent { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public string CreateByMemNumber { get; set; }
        public string ShipVIA { get; set; }
        public string ShippingAddress { get; set; }
        public string BundelStatus { get; set; }
        public string StatusHistory { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public string Note_Packaging { get; set; }
        public string Note_Delivery { get; set; }
        public Nullable<long> InvoiceNumber { get; set; }
        public string DeploymentStatus { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<bool> Renewal { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentNote { get; set; }
        public string PartnerCode { get; set; }
        public Nullable<bool> CreateDeployTicket { get; set; }
    }
}
