//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_UPSPackage
    {
        public string Id { get; set; }
        public string OrderUPSTrackingId { get; set; }
        public string PackageWeight { get; set; }
        public string ImageLabelBase64 { get; set; }
        public string PackageType { get; set; }
    }
}
