//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Subcription
    {
        public long Id { get; set; }
        public string StoreCode { get; set; }
        public string OrderCode { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Period { get; set; }
        public Nullable<System.DateTime> PurcharsedDay { get; set; }
        public Nullable<int> NumberOfItem { get; set; }
        public Nullable<bool> AutoRenew { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<bool> Actived { get; set; }
        public Nullable<bool> IsAddon { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Product_Code { get; set; }
        public string Product_Code_POSSystem { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public string PriceType { get; set; }
        public Nullable<int> Promotion_Apply_Months { get; set; }
        public string SubscriptionType { get; set; }
        public Nullable<bool> ApplyDiscountAsRecurring { get; set; }
        public string PeriodRecurring { get; set; }
        public Nullable<int> SubscriptionQuantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
