//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_BankSupport
    {
        public string Code { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public Nullable<short> Type { get; set; }
        public string Method { get; set; }
        public string Logo { get; set; }
        public string Url { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<bool> IsNapas { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdateBy { get; set; }
        public string BankDDA { get; set; }
        public string BankAccountRouting { get; set; }
        public string Comment { get; set; }
    }
}
