//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_BonusStrategySetting
    {
        public long Id { get; set; }
        public string StrategyName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Opt_TotalIncome_EqualOrThan { get; set; }
        public Nullable<int> Opt_NewMemberTotal_EqualOrThan { get; set; }
        public Nullable<bool> Active { get; set; }
        public string ApplyForMemberType { get; set; }
        public Nullable<decimal> BonusAmount { get; set; }
        public string Comment { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<int> Opt_TotalQuantityFullContracts_EqualOrThan { get; set; }
        public string ApplyByTerm { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string ApplyForMemberType_Name { get; set; }
    }
}
