//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_MemberLevel
    {
        public long Id { get; set; }
        public string MemberNumber { get; set; }
        public string MemberName { get; set; }
        public Nullable<int> LevelNumber { get; set; }
        public string LevelName { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> PromotedAtDate { get; set; }
        public string PromotedBy { get; set; }
    }
}
