//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Notification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_Notification()
        {
            this.P_NotificationMapping = new HashSet<P_NotificationMapping>();
        }
    
        public int Id { get; set; }
        public string MemberNumber { get; set; }
        public string MemberName { get; set; }
        public string Data { get; set; }
        public string Category { get; set; }
        public string Action { get; set; }
        public int TemplateId { get; set; }
        public string EntityId { get; set; }
        public string EntityCode { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> UpdateId { get; set; }
        public string EntityName { get; set; }
    
        public virtual P_NotificationTemplate P_NotificationTemplate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_NotificationMapping> P_NotificationMapping { get; set; }
    }
}
