//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Detail
    {
        public long Id { get; set; }
        public string POCode { get; set; }
        public string RequestCode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Note { get; set; }
        public Nullable<bool> Purchased { get; set; }
        public string ModelCode { get; set; }
        public Nullable<bool> CheckedIn { get; set; }
        public Nullable<System.DateTime> CheckedInDate { get; set; }
        public string InvNumbers { get; set; }
        public Nullable<int> RemainQty { get; set; }
        public string ModelPicture { get; set; }
        public string ModelName { get; set; }
    }
}
