//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PO_Request
    {
        public string Code { get; set; }
        public string ModelCode { get; set; }
        public string ModelPicture { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Color { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Purchased { get; set; }
        public string Note { get; set; }
        public Nullable<long> CreatedbyId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> RequestQty { get; set; }
        public string ModelName { get; set; }
    }
}
