//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store_Services
    {
        public string Id { get; set; }
        public string StoreCode { get; set; }
        public string StoreName { get; set; }
        public string CustomerCode { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> RenewDate { get; set; }
        public string ProductCode { get; set; }
        public string Productname { get; set; }
        public string Type { get; set; }
        public string Period { get; set; }
        public Nullable<bool> AutoRenew { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> LastUpdateAt { get; set; }
        public string LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastRenewAt { get; set; }
        public string LastRenewBy { get; set; }
        public string LastRenewOrderCode { get; set; }
        public Nullable<bool> hasRenewInvoiceIncomplete { get; set; }
        public string OrderCode { get; set; }
        public string Product_Code_POSSystem { get; set; }
        public string StoreApply { get; set; }
        public Nullable<long> MxMerchant_SubscriptionId { get; set; }
        public Nullable<long> MxMerchant_contractId { get; set; }
        public Nullable<long> MxMerchant_cardAccountId { get; set; }
        public string MxMerchant_SubscriptionStatus { get; set; }
        public Nullable<bool> ApplyDiscountAsRecurring { get; set; }
        public string PeriodRecurring { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
