//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FileRelated
    {
        public int Id { get; set; }
        public string Note { get; set; }
        public long TicketId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public string UpdateBy { get; set; }
    
        public virtual T_SupportTicket T_SupportTicket { get; set; }
    }
}
