//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Project_Milestone_Notes
    {
        public string Id { get; set; }
        public string MilestoneId { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public Nullable<int> Order { get; set; }
    }
}
