//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enrich.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TicketFeedback
    {
        public long Id { get; set; }
        public Nullable<long> TicketId { get; set; }
        public string Feedback { get; set; }
        public string CreateByNumber { get; set; }
        public string CreateByName { get; set; }
        public Nullable<System.DateTime> CreateAt { get; set; }
        public string TicketStatusChanges { get; set; }
        public string GlobalStatus { get; set; }
        public Nullable<bool> Share { get; set; }
        public string FeedbackTitle { get; set; }
        public string DateCode { get; set; }
        public string Attachments { get; set; }
        public string UpdatedHistory { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<bool> DisableWriteLog { get; set; }
    }
}
